import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import Logo from "../public/Remove-bg.ai_1701116393719 (1).png"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main_div">
          <div className="max-w-7xl mx-auto p-4 ">
            {/* <Navbar /> */}
            <div className="flex items-end justify-center">
            </div>
            <div className="mt-8">
              {children}
            </div>
            <center className="text-white mt-10">
              <h1 className="text-white text-4xl">DIN ISHLARI BO`YICHA QO`MITA</h1>
              <p>O`zbekiston Respublikasi Oliy sudi tomonidan ekstremizm va terrozizm g`oyalari bilan yo`g`irilgan deb O`zbekiston Respublikasi hududiga olib kirish,tayyorlash,tarqatish va namoyish etish taqiqlangan materiallar ro`yxati (2023 yil 17 may)</p>
            </center>
          </div>
        </div>
      </body>
    </html>
  );
}
